version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/python:3.6.3
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            cd rest-api
            sudo pip install -r requirements.txt
      - run:
          command: |
            pwd
            ls
            python manage.py test likenpost.apps
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1


