version: '3'

services:

  db:
    image: postgres:10

  rest-api:
    build: ./rest-api
    #command: bash
    #tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./rest-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=likenpost.settings.docker
      - ENV=local

