version: '3'

services:

  db:
    image: postgres:10

  rest-api:
    build: ./rest-api
    command: bash
    tty: true
    #command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rest-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

